apiVersion: v1
kind: PersistentVolume
metadata:
  name: cola-training-workspace-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /home/charles/remotework/cola/runtime/training-pvc
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cola-training-workspace
  namespace: remote-work
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: ""
  volumeName: cola-training-workspace-pv
