CREATE TYPE "public"."cola_agent_role" AS ENUM('product', 'engineering', 'operations', 'hr', 'procurement', 'ceo_office');--> statement-breakpoint
CREATE TYPE "public"."cola_agent_status" AS ENUM('idle', 'planning', 'waiting_device', 'executing', 'waiting_handoff', 'waiting_approval', 'blocked', 'error');--> statement-breakpoint
CREATE TYPE "public"."cola_approval_status" AS ENUM('pending', 'approved', 'rejected', 'canceled');--> statement-breakpoint
CREATE TYPE "public"."cola_approval_type" AS ENUM('production_release', 'vendor_quote', 'offer_release', 'policy_change');--> statement-breakpoint
CREATE TYPE "public"."cola_device_status" AS ENUM('online', 'busy', 'offline', 'unhealthy', 'maintenance');--> statement-breakpoint
CREATE TYPE "public"."cola_device_type" AS ENUM('mac_mini', 'browser_runner', 'sandbox');--> statement-breakpoint
CREATE TYPE "public"."cola_event_severity" AS ENUM('info', 'warning', 'critical');--> statement-breakpoint
CREATE TYPE "public"."cola_priority" AS ENUM('low', 'medium', 'high', 'critical');--> statement-breakpoint
CREATE TYPE "public"."cola_risk_level" AS ENUM('low', 'medium', 'high');--> statement-breakpoint
CREATE TYPE "public"."cola_execution_session_status" AS ENUM('pending', 'starting', 'running', 'succeeded', 'failed', 'canceled');--> statement-breakpoint
CREATE TYPE "public"."cola_task_status" AS ENUM('created', 'queued', 'assigned', 'in_progress', 'pending_approval', 'handed_off', 'completed', 'failed', 'canceled');--> statement-breakpoint
CREATE TYPE "public"."cola_task_type" AS ENUM('feature', 'bugfix', 'campaign', 'recruiting', 'procurement', 'coordination');--> statement-breakpoint
CREATE TYPE "public"."cola_zone" AS ENUM('command', 'product', 'engineering', 'growth', 'people', 'vendor');--> statement-breakpoint
CREATE TABLE "cola_agent" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar(120) NOT NULL,
	"roleType" "cola_agent_role" NOT NULL,
	"status" "cola_agent_status" NOT NULL,
	"zoneId" "cola_zone" NOT NULL,
	"focus" text,
	"capabilities" jsonb,
	"riskScope" jsonb,
	"isEnabled" boolean DEFAULT true NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "cola_approval" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"taskId" uuid,
	"approvalType" "cola_approval_type" NOT NULL,
	"status" "cola_approval_status" DEFAULT 'pending' NOT NULL,
	"requestedByAgentId" uuid,
	"approvedByUserId" varchar(120),
	"title" varchar(160) NOT NULL,
	"reason" text,
	"resolvedAt" timestamp with time zone,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "cola_device" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar(120) NOT NULL,
	"deviceType" "cola_device_type" NOT NULL,
	"status" "cola_device_status" NOT NULL,
	"resourcePool" varchar(120) NOT NULL,
	"host" varchar(255),
	"metadata" jsonb,
	"lastHeartbeatAt" timestamp with time zone,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "cola_event" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"eventType" varchar(120) NOT NULL,
	"entityType" varchar(80) NOT NULL,
	"entityId" varchar(120) NOT NULL,
	"severity" "cola_event_severity" DEFAULT 'info' NOT NULL,
	"title" varchar(160) NOT NULL,
	"description" text,
	"payload" jsonb,
	"occurredAt" timestamp with time zone NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cola_execution_session" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"taskId" uuid,
	"agentId" uuid,
	"deviceId" uuid,
	"status" "cola_execution_session_status" DEFAULT 'pending' NOT NULL,
	"logPath" text,
	"artifactPath" text,
	"startedAt" timestamp with time zone,
	"endedAt" timestamp with time zone,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "cola_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cola_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "cola_task" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"title" varchar(160) NOT NULL,
	"taskType" "cola_task_type" NOT NULL,
	"status" "cola_task_status" NOT NULL,
	"priority" "cola_priority" DEFAULT 'medium' NOT NULL,
	"riskLevel" "cola_risk_level" DEFAULT 'low' NOT NULL,
	"zoneId" "cola_zone" NOT NULL,
	"currentAgentId" uuid,
	"parentTaskId" uuid,
	"inputPayload" jsonb,
	"outputPayload" jsonb,
	"summary" text,
	"dueAt" timestamp with time zone,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "cola_approval" ADD CONSTRAINT "cola_approval_taskId_cola_task_id_fk" FOREIGN KEY ("taskId") REFERENCES "public"."cola_task"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cola_approval" ADD CONSTRAINT "cola_approval_requestedByAgentId_cola_agent_id_fk" FOREIGN KEY ("requestedByAgentId") REFERENCES "public"."cola_agent"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cola_execution_session" ADD CONSTRAINT "cola_execution_session_taskId_cola_task_id_fk" FOREIGN KEY ("taskId") REFERENCES "public"."cola_task"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cola_execution_session" ADD CONSTRAINT "cola_execution_session_agentId_cola_agent_id_fk" FOREIGN KEY ("agentId") REFERENCES "public"."cola_agent"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cola_execution_session" ADD CONSTRAINT "cola_execution_session_deviceId_cola_device_id_fk" FOREIGN KEY ("deviceId") REFERENCES "public"."cola_device"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cola_task" ADD CONSTRAINT "cola_task_currentAgentId_cola_agent_id_fk" FOREIGN KEY ("currentAgentId") REFERENCES "public"."cola_agent"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "agent_role_idx" ON "cola_agent" USING btree ("roleType");--> statement-breakpoint
CREATE INDEX "agent_status_idx" ON "cola_agent" USING btree ("status");--> statement-breakpoint
CREATE INDEX "agent_zone_idx" ON "cola_agent" USING btree ("zoneId");--> statement-breakpoint
CREATE INDEX "approval_status_idx" ON "cola_approval" USING btree ("status");--> statement-breakpoint
CREATE INDEX "approval_task_idx" ON "cola_approval" USING btree ("taskId");--> statement-breakpoint
CREATE INDEX "device_status_idx" ON "cola_device" USING btree ("status");--> statement-breakpoint
CREATE INDEX "device_pool_idx" ON "cola_device" USING btree ("resourcePool");--> statement-breakpoint
CREATE INDEX "event_entity_idx" ON "cola_event" USING btree ("entityType","entityId");--> statement-breakpoint
CREATE INDEX "event_occurred_idx" ON "cola_event" USING btree ("occurredAt");--> statement-breakpoint
CREATE INDEX "execution_session_task_idx" ON "cola_execution_session" USING btree ("taskId");--> statement-breakpoint
CREATE INDEX "execution_session_device_idx" ON "cola_execution_session" USING btree ("deviceId");--> statement-breakpoint
CREATE INDEX "execution_session_status_idx" ON "cola_execution_session" USING btree ("status");--> statement-breakpoint
CREATE INDEX "name_idx" ON "cola_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "task_status_idx" ON "cola_task" USING btree ("status");--> statement-breakpoint
CREATE INDEX "task_agent_idx" ON "cola_task" USING btree ("currentAgentId");--> statement-breakpoint
CREATE INDEX "task_zone_idx" ON "cola_task" USING btree ("zoneId");--> statement-breakpoint
CREATE INDEX "task_risk_idx" ON "cola_task" USING btree ("riskLevel");