CREATE TYPE "public"."cola_cmdb_deploy_target" AS ENUM('k8s', 'ssh', 'docker', 'none');--> statement-breakpoint
CREATE TYPE "public"."cola_cmdb_release_status" AS ENUM('pending', 'running', 'success', 'failed', 'canceled');--> statement-breakpoint
CREATE TABLE "cola_cmdb_project" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cola_cmdb_project_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"gitlabProjectId" integer,
	"gitlabPath" varchar(512) NOT NULL,
	"gitlabWebUrl" text,
	"description" text,
	"defaultBranch" varchar(128) DEFAULT 'main' NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"deployTarget" "cola_cmdb_deploy_target" DEFAULT 'none' NOT NULL,
	"config" jsonb,
	"lastSyncedAt" timestamp with time zone,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "cola_cmdb_project_gitlabPath_unique" UNIQUE("gitlabPath")
);
--> statement-breakpoint
CREATE TABLE "cola_cmdb_release" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cola_cmdb_release_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"projectId" integer NOT NULL,
	"ref" varchar(128) NOT NULL,
	"deployEnv" varchar(64),
	"gitlabPipelineId" integer,
	"gitlabPipelineUrl" text,
	"gitlabStatus" varchar(64),
	"status" "cola_cmdb_release_status" DEFAULT 'pending' NOT NULL,
	"variables" jsonb,
	"triggeredBy" varchar(256),
	"lastError" text,
	"startedAt" timestamp with time zone NOT NULL,
	"completedAt" timestamp with time zone,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "cola_cmdb_release" ADD CONSTRAINT "cola_cmdb_release_projectId_cola_cmdb_project_id_fk" FOREIGN KEY ("projectId") REFERENCES "public"."cola_cmdb_project"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "cmdb_project_name_idx" ON "cola_cmdb_project" USING btree ("name");--> statement-breakpoint
CREATE INDEX "cmdb_project_path_idx" ON "cola_cmdb_project" USING btree ("gitlabPath");--> statement-breakpoint
CREATE INDEX "cmdb_project_enabled_idx" ON "cola_cmdb_project" USING btree ("enabled");--> statement-breakpoint
CREATE INDEX "cmdb_project_target_idx" ON "cola_cmdb_project" USING btree ("deployTarget");--> statement-breakpoint
CREATE INDEX "cmdb_release_project_idx" ON "cola_cmdb_release" USING btree ("projectId");--> statement-breakpoint
CREATE INDEX "cmdb_release_status_idx" ON "cola_cmdb_release" USING btree ("status");--> statement-breakpoint
CREATE INDEX "cmdb_release_created_idx" ON "cola_cmdb_release" USING btree ("createdAt");
