CREATE TYPE "public"."cola_cmdb_asset_status" AS ENUM('connected', 'planned', 'unknown');--> statement-breakpoint
CREATE TABLE "cola_cmdb_asset" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cola_cmdb_asset_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(128) NOT NULL,
	"ip" varchar(128) NOT NULL,
	"sshUser" varchar(128),
	"sshPort" integer DEFAULT 22 NOT NULL,
	"roles" jsonb,
	"arch" varchar(64),
	"status" "cola_cmdb_asset_status" DEFAULT 'connected' NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "cola_cmdb_asset_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE INDEX "cmdb_asset_name_idx" ON "cola_cmdb_asset" USING btree ("name");--> statement-breakpoint
CREATE INDEX "cmdb_asset_status_idx" ON "cola_cmdb_asset" USING btree ("status");--> statement-breakpoint
CREATE INDEX "cmdb_asset_ip_idx" ON "cola_cmdb_asset" USING btree ("ip");
